### PR TITLE
Update README.md

### LINKED ISSUE #11: npm install needed
For beginner users, you might want to document that after the repo is cloned, they have to run 'npm install'.

### PR DESCRIPTION
**Pull request by biganth**
Resolves #11 by adding instructions for npm install.

### CODE REVIEW

**Comment by johnstonbl01** [comment]
Can we add `$` in front of the commands to be consistent with other terminal commands in the README?

**Comment by johnstonbl01** [comment]
For example: `$ npm install`

**Comment by biganth** [comment]
Whoops, fixed.

**Comment by johnstonbl01** [comment]
Awesome! Thanks so much for the contribution! :+1:

**Comment by biganth** [comment]
Thank you, that was my first real PR!

**Comment by johnstonbl01** [comment]
Congrats! Glad I could help introduce you to the world of open source. :smile:

**Pull request merged**
